### ISSUE TITLE
ELIFECYCLE error

### ISSUE THREAD

**Issue by EnzoMartin** [TooTallNate/node-gyp#424]
I've installed all the dependencies, I've tried running it from VS2010 and VS2012 CMD, Python2.7 is in my path, .NET framework is in my path, I just can't seem to get this working on Windows 7 x64.

Not sure what more to try at this point.. Any help would be greatly appreciated

Path if it helps..

```
C:\Ruby200-x64\bin;
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;
C:\Program Files (x86)\ImageMagick-6.8.6-Q16;
C:\Users\emartin\AppData\Roaming\npm;
C:\Program Files\Java\jdk1.7.0_25\bin;
C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;
C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;
C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;
D:\Android\sdk\platform-tools;
C:\HashiCorp\Vagrant\bin;
C:\Program Files (x86)\Git\cmd;
C:\Program Files\nodejs\;
C:\Program Files (x86)\MySQL\MySQL Utilities 1.3.6\;
C:\Python27;
C:\Python27\Lib;
C:\Python27\DLLs;
C:\Python27\Lib\lib-tk;
C:\Windows\System32;
C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;
C:\Windows\Microsoft.NET\Framework\v4.0.30319;
C:\Program Files\TortoiseGit\bin;
C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\x64
```

```
D:\Repos\my-project>npm install passport-ldapauth
npm http GET https://registry.npmjs.org/passport-ldapauth
npm http 304 https://registry.npmjs.org/passport-ldapauth
npm http GET https://registry.npmjs.org/ldapauth-fork
npm http 304 https://registry.npmjs.org/ldapauth-fork
npm http GET https://registry.npmjs.org/ldapjs/0.7.0
npm http GET https://registry.npmjs.org/lru-cache/2.5.0
npm http GET https://registry.npmjs.org/bcrypt/0.7.7
npm http 304 https://registry.npmjs.org/lru-cache/2.5.0
npm http 304 https://registry.npmjs.org/ldapjs/0.7.0
npm http 304 https://registry.npmjs.org/bcrypt/0.7.7
npm http GET https://registry.npmjs.org/bindings/1.0.0
npm http 304 https://registry.npmjs.org/bindings/1.0.0
npm http GET https://registry.npmjs.org/asn1/0.1.11
npm http GET https://registry.npmjs.org/assert-plus/0.1.2
npm http GET https://registry.npmjs.org/buffertools/1.1.0
npm http GET https://registry.npmjs.org/bunyan/0.21.1
npm http GET https://registry.npmjs.org/dtrace-provider/0.2.8
npm http GET https://registry.npmjs.org/pooling/0.4.5
npm http GET https://registry.npmjs.org/nopt/2.1.1

> bcrypt@0.7.7 install D:\Repos\my-project\node_modules\passport-ldapauth\nod
e_modules\ldapauth-fork\node_modules\bcrypt
> node-gyp rebuild


D:\Repos\my-project\node_modules\passport-ldapauth\node_modules\ldapauth-fork
\node_modules\bcrypt>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp
-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: spawn ENOENT
gyp ERR! stack     at errnoException (child_process.js:988:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:779:
34)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Repos\my-project\node_modules\passport-ldapauth\node_modules\
ldapauth-fork\node_modules\bcrypt
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok
npm http 304 https://registry.npmjs.org/bunyan/0.21.1
npm http 304 https://registry.npmjs.org/assert-plus/0.1.2
npm http 304 https://registry.npmjs.org/dtrace-provider/0.2.8
npm http 304 https://registry.npmjs.org/asn1/0.1.11
npm WARN optional dep failed, continuing bcrypt@0.7.7
npm http 304 https://registry.npmjs.org/buffertools/1.1.0
npm http 304 https://registry.npmjs.org/nopt/2.1.1
npm http 304 https://registry.npmjs.org/pooling/0.4.5
npm http GET https://registry.npmjs.org/assert-plus/0.1.4
npm http GET https://registry.npmjs.org/once/1.3.0
npm http GET https://registry.npmjs.org/bunyan/0.22.0
npm http GET https://registry.npmjs.org/vasync/1.4.0
npm http GET https://registry.npmjs.org/abbrev

> buffertools@1.1.0 install D:\Repos\my-project\node_modules\passport-ldapaut
h\node_modules\ldapauth-fork\node_modules\ldapjs\node_modules\buffertools
> node-gyp rebuild


D:\Repos\my-project\node_modules\passport-ldapauth\node_modules\ldapauth-fork
\node_modules\ldapjs\node_modules\buffertools>node "C:\Program Files\nodejs\node
_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebu
ild
gyp ERR! configure error
gyp ERR! stack Error: spawn ENOENT
gyp ERR! stack     at errnoException (child_process.js:988:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:779:
34)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Repos\my-project\node_modules\passport-ldapauth\node_modules\
ldapauth-fork\node_modules\ldapjs\node_modules\buffertools
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok
npm http 304 https://registry.npmjs.org/once/1.3.0
npm http 304 https://registry.npmjs.org/bunyan/0.22.0
npm http 304 https://registry.npmjs.org/assert-plus/0.1.4
npm ERR! Error: ENOENT, open 'D:\Repos\my-project\node_modules\passport-ldapa
uth\node_modules\ldapauth-fork\node_modules\ldapjs\node_modules\bunyan\test\erro
r-event.test.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "passport-ldapauth"
npm ERR! cwd D:\Repos\my-project
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path D:\Repos\my-project\node_modules\passport-ldapauth\node_modules
\ldapauth-fork\node_modules\ldapjs\node_modules\bunyan\test\error-event.test.js
npm ERR! code ENOENT
npm ERR! errno 34
npm http 304 https://registry.npmjs.org/vasync/1.4.0
npm http 304 https://registry.npmjs.org/abbrev
npm ERR! buffertools@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the buffertools@1.1.0 install script.
npm ERR! This is most likely a problem with the buffertools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls buffertools
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "passport-ldapauth"
npm ERR! cwd D:\Repos\my-project
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm http GET https://registry.npmjs.org/jsprim/0.3.0
npm http GET https://registry.npmjs.org/verror/1.1.0
npm http GET https://registry.npmjs.org/mv/0.0.5
npm http 304 https://registry.npmjs.org/jsprim/0.3.0
npm http 304 https://registry.npmjs.org/verror/1.1.0
npm http GET https://registry.npmjs.org/extsprintf/1.0.0
npm http GET https://registry.npmjs.org/json-schema/0.2.2
npm http GET https://registry.npmjs.org/verror/1.3.3
npm http 304 https://registry.npmjs.org/mv/0.0.5
npm http 304 https://registry.npmjs.org/json-schema/0.2.2
npm http 304 https://registry.npmjs.org/verror/1.3.3
npm http 304 https://registry.npmjs.org/extsprintf/1.0.0
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\Repos\my-project\npm-debug.log
npm ERR! not ok code 0

D:\Repos\my-project>
```

**Comment by jcollum** [comment]
@EnzoMartin why did you close this? I'm running into an ELIFECYCLE error as well, your experience may help.

**Comment by EnzoMartin** [comment]
Upgraded the computer to Windows 8 (from 7) and the error disappeared. I was never able to resolve it on the Windows 7 install though, sorry

**Comment by jcollum** [comment]
Ah. My solution to this bug was to install VS 2012 Community. I think it's an error related to a C++ compiler not being present on the system.

**Comment by EnzoMartin** [comment]
I had tried installing both VS2010 and VS2012 and VS2013, made no difference

Invoking node-gyp through the VS command line worked fine though
