### ISSUE TITLE
usage@0.3.9 install script 'node-gyp rebuild'

### ISSUE THREAD

**Issue by DeltaMeter** [TooTallNate/node-gyp#576]
I'm trying to install [pod](https://github.com/yyx990803/pod), and it gives me these errors, something to do with node-gyp. 

```
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/pod/node_modules/pm2/node_modules/usage/.node-gyp"
child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/usr/local/lib/node_modules/pod/node_modules/pm2/node_modules/usage/build'
  CXX(target) Release/obj.target/sysinfo/src/binding.o
../src/binding.cpp: In function ‘void RegisterModule(v8::Handle<v8::Object>)’:
../src/binding.cpp:8:17: error: ‘NewSymbol’ is not a member of ‘v8::String’
     target->Set(String::NewSymbol("HERTZ"), Number::New(sysconf(_SC_CLK_TCK)));
                 ^
../src/binding.cpp:8:77: error: no matching function for call to ‘v8::Number::New(long int)’
     target->Set(String::NewSymbol("HERTZ"), Number::New(sysconf(_SC_CLK_TCK)));
                                                                             ^
../src/binding.cpp:8:77: note: candidate is:
In file included from /usr/local/lib/node_modules/pod/node_modules/pm2/node_modules/usage/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../src/binding.h:1,
                 from ../src/binding.cpp:1:
/usr/local/lib/node_modules/pod/node_modules/pm2/node_modules/usage/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/usr/local/lib/node_modules/pod/node_modules/pm2/node_modules/usage/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note:   candidate expects 2 arguments, 1 provided
../src/binding.cpp:9:17: error: ‘NewSymbol’ is not a member of ‘v8::String’
     target->Set(String::NewSymbol("PAGE_SIZE"), Number::New(sysconf(_SC_PAGESIZE)));
                 ^
../src/binding.cpp:9:82: error: no matching function for call to ‘v8::Number::New(long int)’
     target->Set(String::NewSymbol("PAGE_SIZE"), Number::New(sysconf(_SC_PAGESIZE)));
                                                                                  ^
../src/binding.cpp:9:82: note: candidate is:
In file included from /usr/local/lib/node_modules/pod/node_modules/pm2/node_modules/usage/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../src/binding.h:1,
                 from ../src/binding.cpp:1:
/usr/local/lib/node_modules/pod/node_modules/pm2/node_modules/usage/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/usr/local/lib/node_modules/pod/node_modules/pm2/node_modules/usage/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note:   candidate expects 2 arguments, 1 provided
../src/binding.cpp:17:17: error: ‘NewSymbol’ is not a member of ‘v8::String’
     target->Set(String::NewSymbol("OS"), String::New(OS));
                 ^
../src/binding.cpp:17:42: error: ‘New’ is not a member of ‘v8::String’
     target->Set(String::NewSymbol("OS"), String::New(OS));
                                          ^
make: *** [Release/obj.target/sysinfo/src/binding.o] Error 1
make: Leaving directory `/usr/local/lib/node_modules/pod/node_modules/pm2/node_modules/usage/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.13.0-43-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/pod/node_modules/pm2/node_modules/usage
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Linux 3.13.0-43-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "pod"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! usage@0.3.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the usage@0.3.9 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the usage package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls usage
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
```

Anyone know what's going on?

**Comment by TooTallNate** [comment]
It looks like `node-usage` doesn't work with node v0.11/v0.12 yet. You'll need to create an issue on their bug tracker!
