### ISSUE TITLE
install failed npm .12 using 1.0.3

### ISSUE THREAD

**Issue by robertbaker** [TooTallNate/node-gyp#596]
I have c:\python27

added it to my path and made a PYTHON var.
Also used the set command to set there as well, still failing.

D:\CodeRoot\selenium-webdriver\node_modules\ws\node_modules\utf-8-validate>if no
config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bi
\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (re
gyp ERR! configure error
gyp ERR! stack Error: spawn c:\python27 ENOENT
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_p
:32)
gyp ERR! stack     at child_process.js:1137:20
gyp ERR! stack     at process._tickCallback (node.js:355:11)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\CodeRoot\node_modules\selenium-webdriver\node_modules\ws\node_modules\utf-8-v
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.0.1
npm WARN optional dep failed, continuing utf-8-validate@1.0.1
selenium-webdriver@2.45.1 node_modules\selenium-webdriver
├── tmp@0.0.24
├── adm-zip@0.4.4
├── xml2js@0.4.4 (xmlbuilder@2.6.2, sax@0.6.1)
├── rimraf@2.3.2 (glob@4.5.3)
└── ws@0.7.1 (options@0.0.6, ultron@1.0.1)

**Comment by robertbaker** [comment]
Fixed. 
I had node-gyp installed in my project and via global packages.
npm uninstall node-gyp // project root
npm uninstall node-gyp -g

open cmd, cd to C:\Program Files\nodejs\node_modules\npm

run 
node-gyp --python C:\Python27\python.exe
