### ISSUE TITLE
node-gyp configure error on win7

### ISSUE THREAD

**Issue by jeckbjy** [TooTallNate/node-gyp#617]
E:\study\nodejs\node-addon-examples\1_hello_world\node_0.12>node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.3
gyp info using node@1.8.1 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: spawn C:\Python27 ENOENT
gyp ERR! stack     at exports._errnoException (util.js:749:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:987:32)
gyp ERR! stack     at onErrorNT (child_process.js:1138:16)
gyp ERR! stack     at process._tickCallback (node.js:343:24)
gyp ERR! stack     at Function.Module.runMain (module.js:471:11)
gyp ERR! stack     at startup (node.js:124:18)
gyp ERR! stack     at node.js:882:3
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\Program Files\\iojs\\node.exe" "D:\\Program Files\\iojs\\node_modules\\node-gy
p\\bin\\node-gyp.js" "configure"
gyp ERR! cwd E:\study\nodejs\node-addon-examples\1_hello_world\node_0.12
gyp ERR! node -v v1.8.1
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok

**Comment by jeckbjy** [comment]
i have find the answer:change the environment variables PYTHON
from PYTHON=C:\python\
to PYTHON=C:\python\python.exe
