### ISSUE TITLE
Problem with iron-meteor Windows installation: "This is a bug in 'node-gyp'"

### ISSUE THREAD

**Issue by andiseeowe** [TooTallNate/node-gyp#621]
Good day!
Been needing to install iron-meteor. I tried to do `npm install -g iron-meteor`, I got this:

```
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack TypeError: Invalid Version: 3.5.0a4
gyp ERR! stack     at new SemVer (C:\Program
Files\nodejs\node_modules\npm\node_modules\semver\semver.js:273:11)`
gyp ERR! stack     at Range.test (C:\Program Files\nodejs\node_modules\npm\node_modules\semver\semver.js:998:15)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:94:17
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:735:7)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at maybeClose (child_process.js:1008:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
 ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
```

I updated node-gyp using `npm update node-gyp` after this and tried installing iron-meteor again. Same thing happened.

I have Windows 7 with NPM and Meteor JS installed.

**Comment by ant-fx** [comment]
I had this problem today. It is caused by having a pre-release version of Python installed (in this case 3.5.0a4).

If you uninstall that and just have say 3.4.3 installed it should fix the issue.

**Comment by TooTallNate** [comment]
Try v2.0.1 please!
