### ISSUE TITLE
support python 3

### ISSUE THREAD

**Issue by avelino** [TooTallNate/node-gyp#641]
```
avelino@kml ~/teste-poorny (master) $ npm install
|[[5~|
> node-sass@0.9.6 install /home/avelino/teste-poorny/node_modules/gulp-sass/node_modules/node-sass
> node build.js

child_process: customFds option is deprecated, use stdio instead.
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:14)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:97:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:742:7)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at maybeClose (child_process.js:1015:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
gyp ERR! System Linux 4.0.4-2-ARCH
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/avelino/teste-poorny/node_modules/gulp-sass/node_modules/node-sass
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
Build failed
```

**Comment by TooTallNate** [comment]
Dup of #193.
