### ISSUE TITLE
node-gyp install ECONNRESET issue on Windows 7

### ISSUE THREAD

**Issue by ppalladino** [TooTallNate/node-gyp#645]
While running 'node-gyp install" I get the error below. Looks like the the tarball is downloaded so I am assuming my proxy settings are cool. Any clues would be awesome. Thanks...

Windows 7
python 2.7.10
node v0.12.4
npm 2.10.1
VS 2013
Behind corporate proxy 
All configs are as prescribed in the node-gyp README.md

```
<LOTS OF STUFF> 

gyp verb extracted file from tarball src\node_crypto_bio.h 901
gyp verb extracted file from tarball src\node_constants.h 902
gyp verb extracted file from tarball src\node_watchdog.h 903
gyp verb extracted file from tarball src\node_javascript.h 904

<HANGS HERE FOR ABOUT TEN SECONDS>

gyp WARN install Error: read ECONNRESET
gyp WARN install     at exports._errnoException (util.js:746:11)
gyp WARN install     at TCP.onread (net.js:559:26)
gyp WARN install  got an error, rolling back install { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
gyp verb command remove [ '0.12.4' ]
gyp verb remove using node-gyp dir: C:\Local\Home\.node-gyp
gyp verb remove removing target version: 0.12.4
gyp verb remove removing development files for version: 0.12.4
gyp verb content checksum node-v0.12.4.tar.gz eecc938fec7634262f5da260ed045771bc43a7cd7f8ef710c1126e0ceb46513e
gyp ERR! install error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at TCP.onread (net.js:559:26)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Local\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "-g" "-v" "--force"
gyp ERR! cwd C:\Program Files (x86)\Console2
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
```

**Comment by ppalladino** [comment]
[node-gyp-install](https://www.npmjs.com/package/node-gyp-install)  works perfectly. Why then is there a problem with "node-gyp install"? Also, I logged out the proxyUrl variable and looks good. Any insight or hints about tracking this down would be huge. Thanks!

**Comment by ppalladino** [comment]
Crickets....

**Comment by 2dxgujun** [comment]
Hi, i got the same problem while run `node-gyp install`

- Windows7
- python 2.7.10
- node 0.12.7
- node-gyp 2.0.2

```
D:\WorkSpace\NodejsProjects\microblog\node_modules\mongodb\node_modules\mongodb-c
ore\node_modules\kerberos>node-gyp install
gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.12.7 | win32 | x64
gyp http GET https://nodejs.org/dist/v0.12.7/node-v0.12.7.tar.gz
gyp http 200 https://nodejs.org/dist/v0.12.7/node-v0.12.7.tar.gz
gyp http GET https://nodejs.org/dist/v0.12.7/SHASUMS256.txt
gyp http GET https://nodejs.org/dist/v0.12.7/node.lib
gyp http GET https://nodejs.org/dist/v0.12.7/x64/node.lib
gyp http 200 https://nodejs.org/dist/v0.12.7/SHASUMS256.txt
gyp http 200 https://nodejs.org/dist/v0.12.7/x64/node.lib
gyp http 200 https://nodejs.org/dist/v0.12.7/node.lib
gyp WARN install got an error, rolling back install
gyp ERR! install error
gyp ERR! stack Error: node-v0.12.7.tar.gz local checksum 585520b2b57ba46a3a0060ae
172c142f408c1ef4afda6e3ddef6741343c7e0da not match remote b23d64df051c9c969b0c583
f802d5d71de342e53067127a5061415be7e12f39d
gyp ERR! stack     at deref (C:\Users\PingGe\AppData\Roaming\npm\node_modules\nod
e-gyp\lib\install.js:307:20)
gyp ERR! stack     at Request.<anonymous> (C:\Users\PingGe\AppData\Roaming\npm\no
de_modules\node-gyp\lib\install.js:391:24)
gyp ERR! stack     at Request.emit (events.js:129:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (C:\Users\PingGe\AppData\Roamin
g\npm\node_modules\node-gyp\node_modules\request\request.js:1003:12)
gyp ERR! stack     at IncomingMessage.emit (events.js:129:20)
gyp ERR! stack     at _stream_readable.js:908:16
gyp ERR! stack     at process._tickCallback (node.js:355:11)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Users\\PingGe\\AppData\\Roaming\\npm\\node_modules\\
node-gyp\\bin\\node-gyp.js" "install"
gyp ERR! cwd D:\WorkSpace\NodejsProjects\microblog\node_modules\mongodb\node_modu
les\mongodb-core\node_modules\kerberos
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
```

node-gyp-install works for me, i use china mirrors for node.js org dist.
Is there node-gyp has some way to download from mirrors.

**Comment by rvagg** [comment]
`--dist-url` can be used to override the default of `http://nodejs.org/dist` if you want to use one of the china mirrors

**Comment by 2dxgujun** [comment]
Get it, thank u

**Comment by marco-faustinelli** [comment]
@rvagg - where is this option documented? I cannot find it anywhere on the npm docs.
Please post the complete command line. I tried:

    npm install --dist-url=http://npm.taobao.org/mirror/node --save-dev node-gyp

but it still will go to nodejs.org.

**Comment by rvagg** [comment]
`--dist-url` doesn't pass through npm unfortunately, tbh I'm not sure if there's a path to get it through. You could install `node-gyp` directly `npm install node-gyp -g` and use `node-gyp --dist-url http://foo.bar/` and with node-gyp v3 (out today) you can actually set environment variables for it that'll pass through: `   
NVM_NODEJS_ORG_MIRROR=http://foo.bar npm install whatever`. However, node-gyp v3 isn't in npm yet although it will be shipping baked in to the npm that goes out with Node.js v4 that's out very soon.
